behaviors:
  SphereHunt:
    trainer_type: ppo
    hyperparameters:
      batch_size: 256
      buffer_size: 10240
      learning_rate: 3.0e-4
      beta: 5.0e-3
      epsilon: 0.4
      lambd: 0.99
      num_epoch: 3
      learning_rate_schedule: linear
      beta_schedule: constant
      epsilon_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 128
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 0.1
      gail:
        strength: 0.6
        demo_path: C:\Users\franc\Documents\programming_projects\unity_course\unity_ml_agents\rl_unity_project\rl_unity_project\Assets\ML-Agents\Examples\SphereHunt\demonstrations\demonstrations_0.demo
    behavioral_cloning:
      strength: 0.9
      demo_path: C:\Users\franc\Documents\programming_projects\unity_course\unity_ml_agents\rl_unity_project\rl_unity_project\Assets\ML-Agents\Examples\SphereHunt\demonstrations\demonstrations_0.demo
    max_steps: 100000
    time_horizon: 64
    summary_freq: 10000